MOB-439: Access token refreshing
IDme/ID.me-WebVerify-SDK-iOS pull request #22
Opened 2017-02-22 19:34 UTC by mats-claassen

Fixes #7 

## Description
Access token refreshing implemented using the OAuth flow.
The expiration date of the refresh token is also saved so that if the refresh token is expired then the SDK can return an error immediately

## Todos
- [ ] Tests
- [ ] Documentation

2017-02-22 20:35 UTC, m-revetria requested changes

2017-02-22 20:35 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +    NSString* token = [self.keychainData accessTokenForScope:scope];
shouldn't you use `latestScope` instead of `scope` here?

2017-02-22 20:35 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerifyKeychainData.m
> +#define IDME_REFRESH_EXPIRATION_DATE            @"IDME_REFRESH_EXPIRATION_DATE"
when you load scope tokens from keychain, are you loading this new property?

2017-02-22 20:35 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +- (void)saveDataFromJson:(NSDictionary* _Nonnull)json {
It is not clear enough what this function is expecting/saving just by reading its name. Please consider changing it for something more descriptive

2017-02-22 20:35 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +- (void)refreshTokenForScope:(NSString* _Nonnull)scope callback:(IDmeVerifyWebVerifyTokenResults _Nonnull)callback {
`getAccessTokenWithScope` accepts a nullable scope value. Shouldn't this be similar to be consistent?

2017-02-22 20:35 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +            [self refreshTokenForScope:scope callback:callback];
here too, `latestScope` vs `scope`?

2017-02-22 20:35 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +#define GET_METHOD         @"GET"
this doesn't seem to be used

2017-02-22 20:35 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +#define IDME_WEB_VERIFY_REFRESH_CODE_URL                IDME_WEB_VERIFY_BASE_URL @"oauth/token"
please keep this alphabetically sorted

2017-02-22 20:35 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +#define IDME_WEB_VERIFY_REFRESH_TOKEN_PARAM             @"refresh_token"
order here too

2017-02-23 13:37 UTC, mats-claassen commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +- (void)refreshTokenForScope:(NSString* _Nonnull)scope callback:(IDmeVerifyWebVerifyTokenResults _Nonnull)callback {
I do not think so. This method is just called internally and only if there is a scope (either passed to `getAccesToken` or  the latest used scope from the keychain)

2017-02-23 14:16 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +- (void)saveKeychainDataFromJson:(NSDictionary* _Nonnull)json scope:(NSString* _Nonnull)scope {
I was thinking something like `saveTokenDataFromJson`, I think it's more clear, if you read it then you will know that this functions expect a JSON representation of a token object (access token + refresh token + etc.) What do you think?

2017-02-23 14:16 UTC, m-revetria commented on ID.me WebVerify SDK/IDmeWebVerifyKeychainData.m
> +#define IDME_REFRESH_EXPIRATION_DATE            @"IDME_REFRESH_EXPIRATION_DATE"
What about this?

2017-02-23 14:18 UTC, sdownie approved these changes

2017-02-23 14:26 UTC, mats-claassen commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +- (void)saveKeychainDataFromJson:(NSDictionary* _Nonnull)json scope:(NSString* _Nonnull)scope {
Sounds good.

2017-02-23 15:06 UTC, mats-claassen commented on ID.me WebVerify SDK/IDmeWebVerifyKeychainData.m
> +#define IDME_REFRESH_EXPIRATION_DATE            @"IDME_REFRESH_EXPIRATION_DATE"
Yes, it is loaded.
I load a dictionary and save it directly in `tokensByScope` that is why this variable is not used when loading

2017-02-23 15:08 UTC, m-revetria approved these changes

2017-02-23 15:30 UTC, merged