[WIP] MOB-588: Added default page when there is not internet connection
IDme/ID.me-WebVerify-SDK-iOS pull request #24
Opened 2017-03-01 18:14 UTC by m-revetria

Fixes [MOB-588: iOS 10 - IDP sign in screen frozen when network signal lost](https://idmeinc.atlassian.net/browse/MOB-588)

## Description
Added default page that is shown in case of error when the device is not connected to internet. This default page has a retry button that will reload the last request. This gives the user the ability to retry when the device connects again.

## Changes proposed in this request:
* Added a loading indicator in the web view. This indicator is shown the first time the web view is loading a request and it is dismissed after that request has finished.
* Refactor around WebView delegates implementation. Moved that logic away from `IDmeWebVerify` class and encapsulated in a the new class `IDmeAuthenticationDelegate`.
* Refactor `IDmeWebVerify` to get rid of multiple instance variables.
* Renamed some classes in order to let all classes' name start with prefix `IDme` to prevent name collision issues

## Todos
- [ ] Tests
- [ ] Documentation

2017-03-01 19:42 UTC, sdownie approved these changes

2017-03-01 20:31 UTC, mats-claassen requested changes

2017-03-01 20:31 UTC, mats-claassen commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +#define IDME_WEB_VERIFY_BASE_URL                        @"https://api.idmelabs.com/"
Please undo this

2017-03-01 20:31 UTC, mats-claassen commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +        self.errorPageDescription = NSLocalizedString(@"ID.me requires a connection to the internet.", @"IDme WebVerify SDK disconnected page description");
@sdownie This changed to "ID.me Wallet requires an internet connection", right?

2017-03-01 20:31 UTC, mats-claassen commented on ID.me WebVerify SDK/IDmeWebView.m
> +    [retryButton setTitle:@"Retry" forState:UIControlStateNormal];
Should texts be localized? Not sure if the texts were in the rest of the SDK

2017-03-01 20:48 UTC, sdownie commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +        self.errorPageDescription = NSLocalizedString(@"ID.me requires a connection to the internet.", @"IDme WebVerify SDK disconnected page description");
@mats-claassen Yes

2017-03-01 20:49 UTC, sdownie requested changes
Fix comments

2017-03-01 20:49 UTC, sdownie commented on ID.me WebVerify SDK/IDmeWebView.m
> +    [retryButton setTitle:@"Retry" forState:UIControlStateNormal];
@mats-claassen Don't need to be localized at this point

2017-03-02 12:54 UTC, mats-claassen approved these changes

2017-03-02 15:56 UTC, sdownie approved these changes

2017-03-02 16:01 UTC, merged