MOB-624: User session saved in SDK
IDme/ID.me-WebVerify-SDK-iOS pull request #31
Opened 2017-03-06 15:19 UTC by mats-claassen

Fixes [MOB-624 User session not recognized in IDP signin to add MyID](https://idmeinc.atlassian.net/browse/MOB-624)

## Description
Cookies are used when the user is logged in. When the user logs out then they are removed.

## Todos
- [ ] Tests
- [ ] Documentation

2017-03-06 19:31 UTC, sdownie approved these changes

2017-03-06 19:32 UTC, sdownie commented
@mats-claassen Need changelog entry

2017-03-06 19:42 UTC, sdownie requested changes
Add changelog

2017-03-06 19:59 UTC, m-revetria approved these changes

2017-03-07 15:04 UTC, mats-claassen commented
Changelog is added in #32 including this commit

2017-03-08 14:38 UTC, sdownie approved these changes

2017-03-08 15:41 UTC, merged