MOB-686: Using SFSafariViewController to authenticate the user.
IDme/ID.me-WebVerify-SDK-iOS pull request #33
Opened 2017-03-15 19:17 UTC by m-revetria

Fixes [MOB-686: SDK - Handle authentication in Safari](https://idmeinc.atlassian.net/secure/RapidBoard.jspa?rapidView=127&projectKey=MOB&view=detail&selectedIssue=MOB-686).

## Description
This makes the SDK in compliance with Google's new policies regarding mobile authentication

## Changes proposed in this request:
* Removed all code related to handling login through UKWebView (delegates, custom web view subclass, etc.)
* Removed loading indicator and error page from web view. SFSafariViewController shows its own error page in case of missing internet connection. It also has its own way to let the user know that a request is being loaded.

2017-03-15 19:19 UTC, sdownie approved these changes

2017-03-16 12:35 UTC, mats-claassen requested changes

2017-03-16 12:35 UTC, mats-claassen commented on Sample Project/WebVerifySample/WebVerifySample-Info.plist
> +	<string>https://api.idmelabs.com</string>
I think these two lines do not have to be commited

2017-03-16 13:46 UTC, mats-claassen commented
Also I think there are two more things we have to add here. One is handling the case when the user taps `Done` in the SafariViewController and therefore cancels the process.
The other thing is PKCE.

2017-03-16 14:10 UTC, m-revetria commented
@mats-claassen regarding the case where the user taps the *Done* button, it is already implemented here https://github.com/IDme/ID.me-WebVerify-SDK-iOS/pull/33/files#diff-0e6275c02219dd18d7dce07374b960dcR427. I just have to remove the TODO comment.

2017-03-16 14:31 UTC, mats-claassen commented
Ah OK. Did not see that 👍

2017-03-16 19:20 UTC, mats-claassen commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +    NSAssert(self.safariViewController == nil, @"There is an authentication flow in progress. You should not call IDmeWebVerify.verifyUserInViewController:scope:withTokenResult until the previous has
Maybe it would be better to return an error instead of an assertion failure. What do you think?

2017-03-16 19:20 UTC, mats-claassen commented on ID.me WebVerify SDK/IDmeWebVerify.m
> +                                      [weakSelf callWebVerificationResultsWithToken:nil error:callbackError];
I think there might be a race condition in that `_safariViewController` is set to nil before calling this and therefore a new request might have overriden the callback. Maybe we need a boolean flag to signal if a new request can open the SafariViewController and not check for it to be nil.

2017-03-17 15:00 UTC, mats-claassen approved these changes

2017-03-17 15:06 UTC, merged