Release 4.0.0
IDme/ID.me-WebVerify-SDK-iOS pull request #34
Opened 2017-03-28 15:08 UTC by mats-claassen

Changes:

- MOB-686: Using SFSafariViewController to authenticate the user.
- MOB-624: User session cookie saved in SDK
- MOB-660: Improve error handling in SDK (#27, #29, #30)
- MOB-438: Support different domains for production and development (#25)
- MOB-588: Added default page when there is not internet connection (#24, #26, #28)
- MOB-439: Access token refreshing (#22)
- MOB-596: Create function with login type (sign up or sign in) (#21)
- MOB-573: Add back button to web view (#20)
- MOB-570: Open new tabs in Safari (#19)
- MOB-559: Make navigation bar cancel button optional (#17)
- MOB-533: Added API for adding a new ID (affiliation) (#15)
- MOB-534: Added API for adding a new Login (connection) (#14)
- MOB-442: Remove code that replaces null values with “Unknown” (#10)
- MOB-415: Add access to access token and save it in the keychain (#11)
- MOB-441: Change UIWebView for WKWebView (#12)

2017-03-28 15:09 UTC, sdownie approved these changes

2017-03-28 16:26 UTC, sdownie approved these changes

2017-03-28 17:50 UTC, m-revetria commented on README.md
> +If your app suuports a lower iOS version than 9.0 then you must also add these methods:
misspelling: *supports*

2017-03-28 17:50 UTC, m-revetria commented on README.md
> +    let handled = IDmeWebVerify.sharedInstance().application(app, open: url, options: options)
`options` is not defined in this scope

2017-03-28 17:50 UTC, m-revetria commented on README.md
> +    let handled = IDmeWebVerify.sharedInstance().application(app, open: url, options: options)
`options` is not defined in this scope

2017-03-28 17:50 UTC, m-revetria commented on README.md
> +### Step 1
I would move this point to the installation section

2017-03-28 17:50 UTC, m-revetria commented on README.md
> +You must call `IDmeWebVerify.initialize(withClientID: String, clientSecret: String, redirectURI: String)` before using the SDK. You can do it in `application(didFinishLaunchingWithOptions:)` for exam
I would include the import statement as part of the example code

2017-03-28 17:50 UTC, m-revetria commented on README.md
> +Verification occurs through a SFSafariViewController which will open Safari for the user to log in. You must call `verifyUser(in: UIViewController, scope: String, withTokenResult: IDmeVerifyWebVerify
Maybe you can link the RFC to give more context on why this was changed

2017-03-28 17:53 UTC, sdownie commented on README.md
> +You must handle the redirect calls from the SDK. For this you have to add your `redirectURI` as handled URL scheme. Go to *Project Navigator* -> *Select your target* -> *Info* -> *URL Types* -> *New*
@mats-claassen Typo "as handled URL scheme"

2017-03-28 17:54 UTC, sdownie commented on README.md
> +For example: if your redirectURI is `my_custom_scheme://callback`, enter `my_custom_scheme` in *URL Schemes*.
@mats-claassen  Rename "For example" to "Example"

2017-03-28 20:14 UTC, m-revetria commented on README.md
> +You must call `IDmeWebVerify.initialize(withClientID: String, clientSecret: String, redirectURI: String)` before using the SDK. You can do it in `application(didFinishLaunchingWithOptions:)` for exam
Maybe you can add an explanation on what are those parameters, https://github.com/IDme/ID.me-WebVerify-SDK-Android/pull/33/files#diff-04c6e90faac2675aa89e2176d2eec7d8R84

2017-03-28 20:27 UTC, sdownie requested changes
see comments

2017-03-28 20:34 UTC, matir91 commented on README.md
> +The changelog can be found in [CHANGELOG.md](https://github.com/IDme/ID.me-WebVerify-SDK-iOS/blob/master/CHANGELOG.md)
you shouldn't use the full path

2017-03-29 18:23 UTC, sdownie approved these changes

2017-03-29 19:32 UTC, merged